import type { Metadata } from "next";
import "./globals.css";
import { verifyTokenForPage } from "@/utils/verifyToken";
import { cookies } from "next/headers";
import Header from "@/components/HomeComponents/Nvb";

export const metadata: Metadata = {
  title: "Youssef",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const cookieStore = await cookies();
  const token = cookieStore.get('jwtToken')?.value;
  const userPayload = verifyTokenForPage(token as string)
  const isAdmin = userPayload?.isAdmin as boolean

  return (
    <html lang="en">
      <body>
        <main className=" w-full bg-gray-900 border-b-2 border-gray-800 bg-opacity-90 backdrop-blur-sm shadow-md overflow-visible sticky top-0 z-50">
            <Header admin={isAdmin} />
        </main>
          <div>
            {children}
          </div>
      </body>
    </html>
  );
}
