import type { Metadata } from "next";
import "./globals.css";
import { verifyTokenForPage } from "@/utils/verifyToken";
import { cookies } from "next/headers";
import Header from "@/components/HomeComponents/Nvb";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get('jwtToken')?.value;
  const userPayload = verifyTokenForPage(token as string)
  const isAdmin = userPayload?.isAdmin as boolean

  return (
    <html lang="en">
      <body>
        <Header admin={isAdmin} />
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
